some more small cleanups of code for non-supported systems and convert tabs to spaces
git-svn-id: http://arthurdejong.org/svn/nss-pam-ldapd/libnss_ldapd@13 ef36b2f9-881f-0410-afb5-c4e39611909c

diff --git a/certutil b/certutil
--- a/certutil
+++ b/certutil
@@ -61,7 +61,7 @@
 
 # Print usage
 usage() {
-	cat << EOF
+        cat << EOF
 
 Usage: $0 -l [-d dir]
           -a -n name -i file [-d dir]
@@ -80,64 +80,64 @@ Usage: $0 -l [-d dir]
           file -- Certificate file in PEM format
 
 EOF
-	exit 1
+        exit 1
 }
 
 # Check path
 check_path() {
 
-	# check the directory
-	if [ ! -d $CDIR -a $ADD -eq 1 ]; then
-		echo -n "$0: cannot access $CDIR, create? [y/N] "
-		read LINE
-		case $LINE in
-			y|Y)
-				mkdir $CDIR
-				chmod 700 $CDIR
-				touch $CDIR/certs.dat
-				chmod 600 $CDIR/certs.dat
-				;;
-			*)
-				exit 1
-				;;
-		esac
-	fi
+        # check the directory
+        if [ ! -d $CDIR -a $ADD -eq 1 ]; then
+                echo -n "$0: cannot access $CDIR, create? [y/N] "
+                read LINE
+                case $LINE in
+                        y|Y)
+                                mkdir $CDIR
+                                chmod 700 $CDIR
+                                touch $CDIR/certs.dat
+                                chmod 600 $CDIR/certs.dat
+                                ;;
+                        *)
+                                exit 1
+                                ;;
+                esac
+        fi
 
-	# check certs.dat
-	if [ ! -e $CDIR/certs.dat ]; then
-		echo "$0: please specify a valid cert directory"
-		exit 1
-	fi
+        # check certs.dat
+        if [ ! -e $CDIR/certs.dat ]; then
+                echo "$0: please specify a valid cert directory"
+                exit 1
+        fi
 }
 
 # Add certificates
 add_cert() {
-	check_path
-	if [ ! -e $FILE ]; then	
-		echo "$0: cannot find $FILE"
-		exit 1
-	fi
-	HASH=`openssl x509 -in $FILE -hash -noout 2>/dev/null`.0
-	if [ $? -ne 0 ]; then
-		echo "$0: unable to load certificate $FILE"
-		exit 1
-	fi
+        check_path
+        if [ ! -e $FILE ]; then 
+                echo "$0: cannot find $FILE"
+                exit 1
+        fi
+        HASH=`openssl x509 -in $FILE -hash -noout 2>/dev/null`.0
+        if [ $? -ne 0 ]; then
+                echo "$0: unable to load certificate $FILE"
+                exit 1
+        fi
 
-	if grep "^$CNAME|" $CDIR/certs.dat 1>/dev/null 2>&1; then
-		echo "$0: nickname already in use"
-		exit 1
-	fi
+        if grep "^$CNAME|" $CDIR/certs.dat 1>/dev/null 2>&1; then
+                echo "$0: nickname already in use"
+                exit 1
+        fi
 
-	if [ -e $CDIR/$HASH ]; then
-		echo "$0: certificate already in directory"
-		echo `openssl x509 -in $CDIR/$HASH -subject -noout`
-		exit 1
-	else
-		cp $FILE $CDIR/$HASH
-		chmod 600 $CDIR/$HASH
-		echo "$CNAME|$HASH" >> $CDIR/certs.dat
-		chmod 600 $CDIR/certs.dat
-	fi
+        if [ -e $CDIR/$HASH ]; then
+                echo "$0: certificate already in directory"
+                echo `openssl x509 -in $CDIR/$HASH -subject -noout`
+                exit 1
+        else
+                cp $FILE $CDIR/$HASH
+                chmod 600 $CDIR/$HASH
+                echo "$CNAME|$HASH" >> $CDIR/certs.dat
+                chmod 600 $CDIR/certs.dat
+        fi
 
 }
 
@@ -146,52 +146,52 @@ add_cert() {
 # (this is too slow...)
 #
 list_cert() {
-	check_path
-	echo
-	echo "Certificates in directory $CDIR"
-	echo
-	printf "%-30s%s\n" nickname subject/issuer
-	echo "----------------------------------------------------------------------------"
-	cat $CDIR/certs.dat | while read LINE; do
-		NICK=`echo $LINE | cut -d "|" -f 1`
-		HASH=`echo $LINE | cut -d "|" -f 2`
-		SUBJECT=`openssl x509 -in $CDIR/$HASH -subject -noout`
-		ISSUER=`openssl x509 -in $CDIR/$HASH -issuer -noout`
-		printf "%-30s%s\n" "$NICK" "$SUBJECT"
-		printf "%-30s%s\n\n" "" "$ISSUER"
+        check_path
+        echo
+        echo "Certificates in directory $CDIR"
+        echo
+        printf "%-30s%s\n" nickname subject/issuer
+        echo "----------------------------------------------------------------------------"
+        cat $CDIR/certs.dat | while read LINE; do
+                NICK=`echo $LINE | cut -d "|" -f 1`
+                HASH=`echo $LINE | cut -d "|" -f 2`
+                SUBJECT=`openssl x509 -in $CDIR/$HASH -subject -noout`
+                ISSUER=`openssl x509 -in $CDIR/$HASH -issuer -noout`
+                printf "%-30s%s\n" "$NICK" "$SUBJECT"
+                printf "%-30s%s\n\n" "" "$ISSUER"
 
-	done
+        done
 }
 
 # Remove certificates
 remove_cert() {
-	check_path
-	(
-	cat $CDIR/certs.dat | while read LINE; do
-		NICK=`echo $LINE | cut -d "|" -f 1`
-		HASH=`echo $LINE | cut -d "|" -f 2`
-		if [ "$CNAME" = "$NICK" ]; then
-			rm $CDIR/$HASH
-		else
-			echo $LINE
-		fi
-	done
-	) > /tmp/$$
-	mv /tmp/$$ $CDIR/certs.dat
-	chmod 600 $CDIR/certs.dat
+        check_path
+        (
+        cat $CDIR/certs.dat | while read LINE; do
+                NICK=`echo $LINE | cut -d "|" -f 1`
+                HASH=`echo $LINE | cut -d "|" -f 2`
+                if [ "$CNAME" = "$NICK" ]; then
+                        rm $CDIR/$HASH
+                else
+                        echo $LINE
+                fi
+        done
+        ) > /tmp/$$
+        mv /tmp/$$ $CDIR/certs.dat
+        chmod 600 $CDIR/certs.dat
 }
 
 # View certificate
 view_cert() {
-	check_path
-	cat $CDIR/certs.dat | while read LINE; do
-		NICK=`echo $LINE | cut -d "|" -f 1`
-		HASH=`echo $LINE | cut -d "|" -f 2`
-		if [ "$CNAME" = "$NICK" ]; then
-			openssl x509 -in $CDIR/$HASH -text
-			return 1
-		fi
-	done
+        check_path
+        cat $CDIR/certs.dat | while read LINE; do
+                NICK=`echo $LINE | cut -d "|" -f 1`
+                HASH=`echo $LINE | cut -d "|" -f 2`
+                if [ "$CNAME" = "$NICK" ]; then
+                        openssl x509 -in $CDIR/$HASH -text
+                        return 1
+                fi
+        done
 }
 
 # Parse option string
@@ -200,32 +200,32 @@ REMOVE=0
 LIST=0
 VIEW=0
 while getopts "arlvd:n:i:" OPT; do
-	case $OPT in
-		a)
-			ADD=1
-			;;
-		r)
-			REMOVE=1
-			;;
-		l)
-			LIST=1
-			;;
-		v)
-			VIEW=1
-			;;
-		d)
-			CDIR=$OPTARG
-			;;
-		n)
-			CNAME=$OPTARG
-			;;
-		i)
-			FILE=$OPTARG
-			;;
-		*)
-			usage
-			;;
-	esac
+        case $OPT in
+                a)
+                        ADD=1
+                        ;;
+                r)
+                        REMOVE=1
+                        ;;
+                l)
+                        LIST=1
+                        ;;
+                v)
+                        VIEW=1
+                        ;;
+                d)
+                        CDIR=$OPTARG
+                        ;;
+                n)
+                        CNAME=$OPTARG
+                        ;;
+                i)
+                        FILE=$OPTARG
+                        ;;
+                *)
+                        usage
+                        ;;
+        esac
 done
 
 # Default options
@@ -233,31 +233,31 @@ CDIR=${CDIR:=.}
 
 # Check command line options
 if [ $ADD -eq 1 -a $REMOVE -eq 0 -a $LIST -eq 0 -a $VIEW -eq 0 ]; then
-	if [ -n "$CNAME" -a -n "$FILE" ]; then
-		add_cert
-	else
-		echo "$0: missing certificate name or file"
-		usage
-	fi
+        if [ -n "$CNAME" -a -n "$FILE" ]; then
+                add_cert
+        else
+                echo "$0: missing certificate name or file"
+                usage
+        fi
 elif [ $REMOVE -eq 1 -a $ADD -eq 0 -a $LIST -eq 0 -a $VIEW -eq 0 ]; then
-	if [ -n "$CNAME" ]; then
-		remove_cert
-	else
-		echo "$0: missing certificate name"
-		usage
-	fi
+        if [ -n "$CNAME" ]; then
+                remove_cert
+        else
+                echo "$0: missing certificate name"
+                usage
+        fi
 elif [ $LIST -eq 1 -a $ADD -eq 0 -a $REMOVE -eq 0 -a $VIEW -eq 0 ]; then
-	list_cert
+        list_cert
 elif [ $VIEW -eq 1 -a $ADD -eq 0 -a $REMOVE -eq 0 -a $LIST -eq 0 ]; then
-	if [ -n "$CNAME" ]; then
-		if view_cert; then
-			echo "$0: cert named \"$CNAME\" not found"
-			exit 1
-		fi
-	else
-		echo "$0: missing certificate name"
-		usage
-	fi
+        if [ -n "$CNAME" ]; then
+                if view_cert; then
+                        echo "$0: cert named \"$CNAME\" not found"
+                        exit 1
+                fi
+        else
+                echo "$0: missing certificate name"
+                usage
+        fi
 else
-	usage
+        usage
 fi
